### Problem 0

In [30]:
import numpy as np
import pandas as pd
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]
clean = pd.read_csv('lab data/data_clean.csv')
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    object
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), object(1)
memory usage: 13.5+ KB

### Problem 1

In [7]:
data1 = pd.read_csv('lab data/data1.csv', header=2)
data1

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

The original data had the headers at row 2, so in order to load the data correctly, the `header` parameter had to be set to 2.

### Problem 2

In [28]:
data2 = pd.read_table('lab data/data2.txt', sep=",", header=2, comment='/')
data2

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

In addition to having the header at row 2, since the data is in a `.txt` file, we used the `read_table()` function instead of the `read_csv()` function, we had to specify that the delimiter is the comma, and we had to specify that comments started with a slash.

### Problem 3

In [31]:
data3 = pd.read_table('lab data/data3.txt', sep='\t', header=2)
data3

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

This data was separated by tabs instead of commas, so we had to change the `sep` parameter to `\t`.

### Problem 4

In [35]:
data4 = pd.read_table('lab data/data4.txt', sep='$', header=None, names=column_names)
data4

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

This data file was missing the names of the columns, so we had to specify the header as `None` and add in the column headers by passing in `column_names` as `names`.

### Problem 5

In [5]:
data5 = pd.read_csv('lab data/data5.csv', skipfooter=2)
data5

C:\Users\berna\AppData\Local\Temp\ipykernel_7140\1587019458.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  data5 = pd.read_csv('lab data/data5.csv', skipfooter=2)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

This data file has a footer, so we had to specify that it had a footer that was two lines that we wanted it to skip.

### Problem 6

In [42]:
data6 = pd.read_table('lab data/data6.dat', sep=",")
data6

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,999.000,999.000,999.000,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,999.000,999.000,1.582,999.000,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,999.000,0.683,0.284,0.408
3,Iceland,7.495,7.593,999.000,2.426,1.343,1.644,0.914,0.677,0.353,999.000
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,999,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,999.000,0.064
152,Tanzania,999.000,999.000,3.193,0.628,999.000,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,999.000,3.123,1.691,0.337,999.000,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,999.000,0.038
155,Burundi,2.905,3.074,999.000,1.752,0.091,999.000,0.145,0.065,0.149,0.076

Because the file ending is `.dat`, we originally tried to open it with the `read_stata()` function. However, since it's an old version of Stata, we had to use the `read_table()` function and specify that the delimiter is the comma.

### Problem 7

In [50]:
data7 = pd.read_excel('lab data/data7.xlsx', sheet_name='Data')
data7

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

I had to run `pip install openpyxl` first in order to run `read_excel()`, and because excel files can contain several sheets, we had to specify the `sheet_name` as `'Data'`.

### Problem 8

In [11]:
data8 = pd.read_stata('lab data/data8.dta')
data8.columns = column_names
data8

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Since the data set is in a `.dta` file, we used the `read_stata()` function to read the file. We also set the column names to `column_names` from above, since the names weren't formatted correctly.

### Problem 9

In [13]:
data9 = pd.read_spss('lab data/data9.sav')
data9.columns = column_names
data9

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Since the data set is in a `.sav` file, we used the `read_sav()` function to read the file. We also set the column names to `column_names` from above, since the names weren't formatted correctly, like in problem 8. I also had to run `pip install pyreadstat` to run `read_sav()`.

### Problem 10

In [23]:
data10 = pd.read_sas('lab data/data10.xpt', encoding='utf-8')
data10.columns = column_names
data10

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

Like the previous two data sets, the `columns` field had to be set to `column_names` because they were not formatted correctly. Since it was an `.xpt` file, the file was read using the `read_sas()` function. The country names were encoded as binary strings, so the encoding parameter had to be set to `'utf-8'`.

### Problem 11

In [28]:
widths = [24,5,5,5,5,5,5,5,5,5,5]
data11 = pd.read_fwf('lab data/data11.txt', names=column_names,widths=widths)
data11

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

The file is a fixed-width file, so I opened the `.txt` file with the `read_fwf()` function. I had to count the widths of the columns, which was simple, since the country names were given 24 characters, and all the numbers were given five characters. I had to pass that information as a list into the `read_fwf()` function.

In [29]:
data11.to_csv('lab data/data11_cleaned.csv', sep=',')